### ISSUE TITLE
Report of Display Issue on Mobile Devices

### ISSUE THREAD

**Issue by alidehkhodaei** [hamidfarmani/github-stats#1]
Hello and thank you for this interesting project. I have noticed an issue and wanted to report it to you. The information is not displayed properly on the phone size. It would be great if this issue could be resolved. Thank you.
![Screenshot_2023-05-08-02-51-59-190_com android chrome](https://user-images.githubusercontent.com/70447283/236707831-07f81ca2-c274-4a19-81d5-8e310ee1cf97.jpg)
![Screenshot_2023-05-08-02-51-53-279_com android chrome](https://user-images.githubusercontent.com/70447283/236707840-b510f1ca-4336-41bc-b11c-4934a7598d7e.jpg)

**Comment by hamidfarmani** [comment]
Thanks for letting me know @alidehkhodaei ! I did a quick fix on them, if you were interested to add a feature, had suggestions or anything, please let me know.
